require 'user.reiend.options'
require 'user.reiend.keymaps'
require 'user.reiend.plugins'
require 'user.reiend.colorschemes'
require 'user.reiend.lualine'
require 'user.reiend.comment'
require 'user.reiend.telescope'
require 'user.reiend.cmp'
require 'user.reiend.autotags'
require 'user.reiend.autopairs'
require 'user.reiend.lsp'
require 'user.reiend.nvim-treesitter'
require 'user.reiend.gitsigns'
require 'user.reiend.presence'
require 'user.reiend.indentline'
require 'user.reiend.gitconflict'
require 'user.reiend.trouble'
require 'user.reiend.bufferline'

-- require 'user.reiend.neoscroll'
-- require "user.reiend.formatter"
-- require "user.reiend.linter"
