require "user.reiend.options"
require "user.reiend.keymaps"
require "user.reiend.plugins"
require "user.reiend.colorschemes"
require "user.reiend.lualine"
require "user.reiend.comment"
require "user.reiend.telescope"
require "user.reiend.cmp"
require "user.reiend.autotags"
require "user.reiend.autopairs"
require "user.reiend.lsp"
require "user.reiend.nvim-treesitter"
-- require "user.reiend.formatter"
-- require "user.reiend.linter"
